---
apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-eea-int
  namespace: eric-eea-ns
stringData:
  password: cmVmdGtuOjAxOjE3MzIzNjU1MzE6a3lrNUlkSXZWSEZwM3ptSHpTajRGbUVCcGxn
  username: eszakri
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-repo-adp
  namespace: eric-eea-ns
stringData:
  password: cmVmdGtuOjAxOjE3MzIyNzYxNTQ6Z2s2TFhUOHByazRWbGRZVXdlVk5nelN0RjlY
  username: eszakri
